export type Stage5ApiBindings = {
  DB: D1Database;
  STRIPE_SECRET_KEY: string;
  STRIPE_WEBHOOK_SECRET: string;
  STRIPE_BYO_UNLOCK_PRICE_ID?: string;
  UI_ORIGIN?: string;
  OPENAI_API_KEY: string;
  ANTHROPIC_API_KEY?: string;
  ELEVENLABS_API_KEY?: string;
  RELAY_SECRET: string;
  DEVICE_TOKEN_SECRET?: string;
  ALLOWED_ORIGINS?: string;
  ADMIN_API_SECRET?: string;
  ADMIN_DEVICE_ID?: string;
  RECONCILE_CRON_ENABLED?: string;
  RECONCILE_CRON_DRY_RUN?: string;
  TRANSCRIPTION_BUCKET: R2Bucket;
  R2_ACCOUNT_ID: string;
  R2_ACCESS_KEY_ID: string;
  R2_SECRET_ACCESS_KEY: string;
  RELAY_TRANSLATION_MAX_INFLIGHT?: string;
  RELAY_TRANSLATION_DISPATCH_BATCH?: string;
  RELAY_TRANSLATION_ALERT_QUEUE_DEPTH?: string;
  RELAY_TRANSLATION_ALERT_COOLDOWN_MS?: string;
  RELAY_TRANSLATION_ALERT_CONSECUTIVE_FAILURES?: string;
  RELAY_TRANSLATION_USER_MAX_ACTIVE?: string;
  RELAY_TRANSLATION_GLOBAL_MAX_PENDING?: string;
  RELAY_TRANSLATION_USER_RATE_WINDOW_SEC?: string;
  RELAY_TRANSLATION_USER_RATE_MAX_REQUESTS?: string;
  MIN_TRANSLATOR_VERSION?: string;
  MIN_TRANSLATOR_VERSION_ENFORCEMENT?: string;
  TRANSLATOR_DOWNLOAD_URL?: string;
};

export type RelayTranslationBindings = Pick<
  Stage5ApiBindings,
  | "RELAY_TRANSLATION_MAX_INFLIGHT"
  | "RELAY_TRANSLATION_DISPATCH_BATCH"
  | "RELAY_TRANSLATION_ALERT_QUEUE_DEPTH"
  | "RELAY_TRANSLATION_ALERT_COOLDOWN_MS"
  | "RELAY_TRANSLATION_ALERT_CONSECUTIVE_FAILURES"
  | "RELAY_TRANSLATION_USER_MAX_ACTIVE"
  | "RELAY_TRANSLATION_GLOBAL_MAX_PENDING"
  | "RELAY_TRANSLATION_USER_RATE_WINDOW_SEC"
  | "RELAY_TRANSLATION_USER_RATE_MAX_REQUESTS"
>;
